### ISSUE TITLE
Neogrok fails to parse Zoekt webserver response

### ISSUE THREAD

**Issue by kusum18** [isker/neogrok#28]
Hi

The latest versions of Neogrok and Zoekt web server are not compatible with each other. The API request is not generating JSON response and is now only returning HTML response which is not parseable on Neogrok and results in no results on UI.

Any help to fix this will be highly appreciated.

**Comment by isker** [comment]
Are you using the exact same flags to zoekt-webserver as the example dockerfiles in this repo do? If you don’t pass the right flags, this is an outcome you can get.

**Comment by isker** [comment]
https://github.com/isker/neogrok/blob/343763a84a32c5ecf204afd4a7d008f4cb084a07/demo/Dockerfile.zoekt#L31

**Comment by kusum18** [comment]
Thank you. 

It will be great to update the homepage.

**Comment by isker** [comment]
It's there: https://github.com/isker/neogrok?tab=readme-ov-file#deploying
